version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - fullstack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - BACKEND_API_URL=http://backend:8080
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
